// calculator-vue-js/src/main/Calculator.vue
<template>
    <div class="calculator">
        <Display :value="displayValue" />
        <Button label="AC" @on-my-click="clearMemory" />
        <Button label="+/-" @on-my-click="setOperation" />
        <Button label="%" @on-my-click="setOperation" />
        <Button label="/" operation @on-my-click="setOperation"/>
        <Button label="7" @on-my-click="addDigit" />
        <Button label="8" @on-my-click="addDigit" />
        <Button label="9" @on-my-click="addDigit" />
        <Button label="x" operation @on-my-click="setOperation" />
        <Button label="4" @on-my-click="addDigit" />
        <Button label="5" @on-my-click="addDigit" />
        <Button label="6" @on-my-click="addDigit" />
        <Button label="-" operation @on-my-click="setOperation" />
        <Button label="1" @on-my-click="addDigit" />
        <Button label="2" @on-my-click="addDigit" />
        <Button label="3" @on-my-click="addDigit" />
        <Button label="+" operation @on-my-click="setOperation" />
        <Button label="0" double @on-my-click="addDigit" />
        <Button label="." @on-my-click="addDigit" />
        <Button label="=" operation @on-my-click="setOperation" />
    </div>
</template>

<script>
import Display from "../components/Display"
import Button from "../components/Button"

export default {
    data: function() {
        return{
            displayValue: "0",
            clearDisplay: false,
            operation: null,
            values: [0, 0],
            current: 0
        }
    },
    components: { Display, Button },
    methods: {
        clearMemory() {
           Object.assign(this.$data, this.$options.data())
        },
        setOperation(operation) {
           if (this.current === 0) {
                this.operation = operation
                this.current = 1
                this.clearDisplay = true
           } else {
                const equals = operation === "="
                const currentOperation = this.operation

                const values = this.values

                switch (currentOperation) {
                    case "/":
                        values[0] /= values[1]
                        values[0] = parseFloat(values[0].toFixed(3))
                        break
                    case "x":
                        values[0] *= values[1]
                        values[0] = parseFloat(values[0].toFixed(3))
                        break
                    case "+":
                        values[0] += values[1]
                        values[0] = parseFloat(values[0].toFixed(3))
                        break
                    case "-":
                        values[0] -= values[1]
                        values[0] = parseFloat(values[0].toFixed(3))
                        break
                    case "%":
                        values[0] /= 100
                        values[0] = parseFloat(values[0].toFixed(3))
                        break
                    case "+/-":
                        values[0] *= -1
                        values[0] = parseFloat(values[0].toFixed(3))
                        break
                    default:                  
                }

               this.values[1] = 0

               this.displayValue = this.values[0]
               this.operation = equals ? null : operation
               this.current = equals ? 0 : 1
               this.clearDisplay = !equals
           }
        },
        addDigit(n) {
            if (n === "." && this.displayValue.includes(".")) {
                return
            }

            const clearDisplay = this.displayValue === "0" || this.clearDisplay
            const currentValue = clearDisplay ? "" : this.displayValue
            const displayValue = currentValue + n
            this.displayValue = displayValue
            this.clearDisplay = false

            if (n !== ".") {
                const i = this.current
                const newValue = parseFloat(displayValue)
                this.values[i] = newValue
            }
        }
    }
}
</script>

<style>
    .calculator {
        height: 320px;
        width: 235px;
        border-radius: 5px;
        overflow: hidden;
        display: grid;
        grid-template-columns: repeat(4,25%);
        grid-template-rows: 1fr 48px 48px 48px 48px 48px;
        margin: 0px 0px 10px 0px;
    }
</style>

// calculator-react-js/src/main/Calculator.jsx
import React, { Component } from 'react';
import './Calculator.css';
import Button from '../components/Button';
import Display from '../components/Display';

const initialState = {
    displayValue: '0',
    clearDisplay: false,
    oepration: null,
    values: [0, 0],
    current: 0
}

export default class Calculator extends Component {
    
    state = { ...initialState }

    constructor(props) {
        super(props)
        this.clearMemory = this.clearMemory.bind(this)
        this.setOperation = this.setOperation.bind(this)
        this.addDigit = this.addDigit.bind(this)
    }

    clearMemory() {
        this.setState({ ...initialState })
    }

    setOperation(operation) {
        if (this.state.current === 0) {
            this.setState({ operation, current: 1, clearDisplay: true} )
        } else {
            const equals = (operation === '=' || operation === '+/-')
          
            const currentOperation = this.state.operation

            const values = [...this.state.values]
            
            switch (currentOperation) {
                case "/":
                    values[0] /= values[1]
                    values[0] = parseFloat(values[0].toFixed(3))
                    break
                case "x":
                    values[0] *= values[1]
                    values[0] = parseFloat(values[0].toFixed(3))
                    break
                case "+":
                    values[0] += values[1]
                    values[0] = parseFloat(values[0].toFixed(3))
                    break
                case "-":
                    values[0] -= values[1]
                    values[0] = parseFloat(values[0].toFixed(3))
                    break
                case "%":
                    values[0] /= 100
                    values[0] = parseFloat(values[0].toFixed(3))
                    break
                case "+/-":
                    values[0] *= -1
                    values[0] = parseFloat(values[0].toFixed(3))
                    break
                default:          
            }

            values[1]=0

            this.setState({
                displayValue: values[0],
                operation: equals ? null : operation,
                current: equals ? 0 : 1,
                clearDisplay: !equals,
                values
            })
        }
    }

    addDigit(n) {
        if (n === '.' && this.state.displayValue.includes('.')) {
            return
        }

        const clearDisplay = this.state.displayValue === '0' || this.state.clearDisplay
        const currentValue = clearDisplay ? '' : this.state.displayValue
        const displayValue = currentValue + n
        this.setState({ displayValue, clearDisplay: false })
    
        if (n !== '.') {
            const i = this.state.current
            const newValue = parseFloat(displayValue)
            const values = [...this.state.values]
            values[i] = newValue
            this.setState({ values })
        }
    }

    render () {
        return (
            <div className="calculator">
                <Display value={this.state.displayValue} />
                <Button label="AC" click={this.clearMemory} />
                <Button label="+/-" click={this.setOperation} />
                <Button label="%" click={this.setOperation} />
                <Button label="/" click={this.setOperation} operation />
                <Button label="7" click={this.addDigit} />
                <Button label="8" click={this.addDigit} />
                <Button label="9" click={this.addDigit} />
                <Button label="x" click={this.setOperation} operation />
                <Button label="4" click={this.addDigit} />
                <Button label="5" click={this.addDigit} />
                <Button label="6" click={this.addDigit} />
                <Button label="-" click={this.setOperation} operation />
                <Button label="1" click={this.addDigit} />
                <Button label="2" click={this.addDigit} />
                <Button label="3" click={this.addDigit} />
                <Button label="+" click={this.setOperation} operation />
                <Button label="0" click={this.addDigit} double />
                <Button label="." click={this.addDigit} />
                <Button label="=" click={this.setOperation} operation />
            </div>
        )
    }
}
